// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
const Verifier = artifacts.require('Verifier');
const proof = require('../../zokrates/code/square/proof.json');

contract('TestVerifier', accounts => {
    const account_one = accounts[0];
    const A = proof["proof"]["A"];
    const B = proof["proof"]["B"];
    const C = proof["proof"]["C"];
    const correctProofInput = proof["input"];
    const incorrectProofInput = [4, 2];

    describe('match verifier spec', function () {
        beforeEach(async function () {
            this.contract = await Verifier.new({from: account_one});
        });

        // Test verification with correct proof
        // - use the contents from proof.json generated from zokrates steps
        it('Test verification with correct proof', async function () {
            let isVerified = await this.contract.verifyTx.call(A, B, C, correctProofInput);
            assert.equal(isVerified, true, "Incorrect proof");
        });

        // Test verification with incorrect proof
        it('Test verification with incorrect proof', async function () {
            let isVerified = await this.contract.verifyTx.call(A, B, C, incorrectProofInput);
            assert.equal(isVerified, false, "Correct proof");
        });
    });
});